language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

script:
  - pip install coverage
  - pip install coveralls
  - coverage run setup.py test
  - coverage report

after_success:
  - coveralls
